/*
    梦幻之星中国 舰船服务器 敌人类型
    版权 (C) 2022, 2023 Sancaros

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License version 3
    as published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "f_logs.h"
#include "pso_text.h"
#include "pso_StringReader.h"

#include "enemy_type.h"

const char* enum_for_name(EnemyType type) {
    switch (type) {
    case NONE:
        return "NONE";
    case UNKNOWN:
        return "UNKNOWN";
    case AL_RAPPY:
        return "AL_RAPPY";
    case ASTARK:
        return "ASTARK";
    case BA_BOOTA:
        return "BA_BOOTA";
    case BARBA_RAY:
        return "BARBA_RAY";
    case BARBAROUS_WOLF:
        return "BARBAROUS_WOLF";
    case BEE_L:
        return "BEE_L";
    case BEE_R:
        return "BEE_R";
    case BOOMA:
        return "BOOMA";
    case BOOTA:
        return "BOOTA";
    case BULCLAW:
        return "BULCLAW";
    case CANADINE:
        return "CANADINE";
    case CANADINE_GROUP:
        return "CANADINE_GROUP";
    case CANANE:
        return "CANANE";
    case CHAOS_BRINGER:
        return "CHAOS_BRINGER";
    case CHAOS_SORCERER:
        return "CHAOS_SORCERER";
    case CLAW:
        return "CLAW";
    case DARK_BELRA:
        return "DARK_BELRA";
    case DARK_FALZ_1:
        return "DARK_FALZ_1";
    case DARK_FALZ_2:
        return "DARK_FALZ_2";
    case DARK_FALZ_3:
        return "DARK_FALZ_3";
    case DARK_GUNNER:
        return "DARK_GUNNER";
    case DARVANT:
        return "DARVANT";
    case DE_ROL_LE:
        return "DE_ROL_LE";
    case DE_ROL_LE_BODY:
        return "DE_ROL_LE_BODY";
    case DE_ROL_LE_MINE:
        return "DE_ROL_LE_MINE";
    case DEATH_GUNNER:
        return "DEATH_GUNNER";
    case DEL_LILY:
        return "DEL_LILY";
    case DEL_RAPPY:
        return "DEL_RAPPY";
    case DEL_RAPPY_ALT:
        return "DEL_RAPPY_ALT";
    case DELBITER:
        return "DELBITER";
    case DELDEPTH:
        return "DELDEPTH";
    case DELSABER:
        return "DELSABER";
    case DIMENIAN:
        return "DIMENIAN";
    case DOLMDARL:
        return "DOLMDARL";
    case DOLMOLM:
        return "DOLMOLM";
    case DORPHON:
        return "DORPHON";
    case DORPHON_ECLAIR:
        return "DORPHON_ECLAIR";
    case DRAGON:
        return "DRAGON";
    case DUBCHIC:
        return "DUBCHIC";
    case DUBWITCH:
        return "DUBWITCH";
    case EGG_RAPPY:
        return "EGG_RAPPY";
    case EPSIGUARD:
        return "EPSIGUARD";
    case EPSILON:
        return "EPSILON";
    case EVIL_SHARK:
        return "EVIL_SHARK";
    case GAEL:
        return "GAEL";
    case GAL_GRYPHON:
        return "GAL_GRYPHON";
    case GARANZ:
        return "GARANZ";
    case GEE:
        return "GEE";
    case GI_GUE:
        return "GI_GUE";
    case GIBBLES:
        return "GIBBLES";
    case GIGOBOOMA:
        return "GIGOBOOMA";
    case GILLCHIC:
        return "GILLCHIC";
    case GIRTABLULU:
        return "GIRTABLULU";
    case GOBOOMA:
        return "GOBOOMA";
    case GOL_DRAGON:
        return "GOL_DRAGON";
    case GORAN:
        return "GORAN";
    case GORAN_DETONATOR:
        return "GORAN_DETONATOR";
    case GRASS_ASSASSIN:
        return "GRASS_ASSASSIN";
    case GUIL_SHARK:
        return "GUIL_SHARK";
    case HALLO_RAPPY:
        return "HALLO_RAPPY";
    case HIDOOM:
        return "HIDOOM";
    case HILDEBEAR:
        return "HILDEBEAR";
    case HILDEBLUE:
        return "HILDEBLUE";
    case ILL_GILL:
        return "ILL_GILL";
    case KONDRIEU:
        return "KONDRIEU";
    case LA_DIMENIAN:
        return "LA_DIMENIAN";
    case LOVE_RAPPY:
        return "LOVE_RAPPY";
    case MERICAROL:
        return "MERICAROL";
    case MERICUS:
        return "MERICUS";
    case MERIKLE:
        return "MERIKLE";
    case MERILLIA:
        return "MERILLIA";
    case MERILTAS:
        return "MERILTAS";
    case MERISSA_A:
        return "MERISSA_A";
    case MERISSA_AA:
        return "MERISSA_AA";
    case MIGIUM:
        return "MIGIUM";
    case MONEST:
        return "MONEST";
    case MORFOS:
        return "MORFOS";
    case MOTHMANT:
        return "MOTHMANT";
    case NANO_DRAGON:
        return "NANO_DRAGON";
    case NAR_LILY:
        return "NAR_LILY";
    case OLGA_FLOW_1:
        return "OLGA_FLOW_1";
    case OLGA_FLOW_2:
        return "OLGA_FLOW_2";
    case PAL_SHARK:
        return "PAL_SHARK";
    case PAN_ARMS:
        return "PAN_ARMS";
    case PAZUZU:
        return "PAZUZU";
    case PAZUZU_ALT:
        return "PAZUZU_ALT";
    case PIG_RAY:
        return "PIG_RAY";
    case POFUILLY_SLIME:
        return "POFUILLY_SLIME";
    case POUILLY_SLIME:
        return "POUILLY_SLIME";
    case POISON_LILY:
        return "POISON_LILY";
    case PYRO_GORAN:
        return "PYRO_GORAN";
    case RAG_RAPPY:
        return "RAG_RAPPY";
    case RECOBOX:
        return "RECOBOX";
    case RECON:
        return "RECON";
    case SAINT_MILLION:
        return "SAINT_MILLION";
    case SAINT_RAPPY:
        return "SAINT_RAPPY";
    case SAND_RAPPY:
        return "SAND_RAPPY";
    case SAND_RAPPY_ALT:
        return "SAND_RAPPY_ALT";
    case SATELLITE_LIZARD:
        return "SATELLITE_LIZARD";
    case SATELLITE_LIZARD_ALT:
        return "SATELLITE_LIZARD_ALT";
    case SAVAGE_WOLF:
        return "SAVAGE_WOLF";
    case SHAMBERTIN:
        return "SHAMBERTIN";
    case SINOW_BEAT:
        return "SINOW_BEAT";
    case SINOW_BERILL:
        return "SINOW_BERILL";
    case SINOW_GOLD:
        return "SINOW_GOLD";
    case SINOW_SPIGELL:
        return "SINOW_SPIGELL";
    case SINOW_ZELE:
        return "SINOW_ZELE";
    case SINOW_ZOA:
        return "SINOW_ZOA";
    case SO_DIMENIAN:
        return "SO_DIMENIAN";
    case UL_GIBBON:
        return "UL_GIBBON";
    case VOL_OPT_1:
        return "VOL_OPT_1";
    case VOL_OPT_2:
        return "VOL_OPT_2";
    case VOL_OPT_AMP:
        return "VOL_OPT_AMP";
    case VOL_OPT_CORE:
        return "VOL_OPT_CORE";
    case VOL_OPT_MONITOR:
        return "VOL_OPT_MONITOR";
    case VOL_OPT_PILLAR:
        return "VOL_OPT_PILLAR";
    case YOWIE:
        return "YOWIE";
    case YOWIE_ALT:
        return "YOWIE_ALT";
    case ZE_BOOTA:
        return "ZE_BOOTA";
    case ZOL_GIBBON:
        return "ZOL_GIBBON";
    case ZU:
        return "ZU";
    case ZU_ALT:
        return "ZU_ALT";
    default:
        ERR_LOG("invalid enemy type");
        return NULL;
    }
}

EnemyType name_for_enemy_type(const char* name) {
    static const EnemyTypeMapping names[] = {
      {"NONE", NONE},
      {"UNKNOWN", UNKNOWN},
      {"AL_RAPPY", AL_RAPPY},
      {"ASTARK", ASTARK},
      {"BA_BOOTA", BA_BOOTA},
      {"BARBA_RAY", BARBA_RAY},
      {"BARBAROUS_WOLF", BARBAROUS_WOLF},
      {"BEE_L", BEE_L},
      {"BEE_R", BEE_R},
      {"BOOMA", BOOMA},
      {"BOOTA", BOOTA},
      {"BULCLAW", BULCLAW},
      {"CANADINE", CANADINE},
      {"CANADINE_GROUP", CANADINE_GROUP},
      {"CANANE", CANANE},
      {"CHAOS_BRINGER", CHAOS_BRINGER},
      {"CHAOS_SORCERER", CHAOS_SORCERER},
      {"CLAW", CLAW},
      {"DARK_BELRA", DARK_BELRA},
      {"DARK_FALZ_1", DARK_FALZ_1},
      {"DARK_FALZ_2", DARK_FALZ_2},
      {"DARK_FALZ_3", DARK_FALZ_3},
      {"DARK_GUNNER", DARK_GUNNER},
      {"DARVANT", DARVANT},
      {"DARVANT_ULTIMATE", DARVANT_ULTIMATE},
      {"DE_ROL_LE", DE_ROL_LE},
      {"DE_ROL_LE_BODY", DE_ROL_LE_BODY},
      {"DE_ROL_LE_MINE", DE_ROL_LE_MINE},
      {"DEATH_GUNNER", DEATH_GUNNER},
      {"DEL_LILY", DEL_LILY},
      {"DEL_RAPPY", DEL_RAPPY},
      {"DEL_RAPPY_ALT", DEL_RAPPY_ALT},
      {"DELBITER", DELBITER},
      {"DELDEPTH", DELDEPTH},
      {"DELSABER", DELSABER},
      {"DIMENIAN", DIMENIAN},
      {"DOLMDARL", DOLMDARL},
      {"DOLMOLM", DOLMOLM},
      {"DORPHON", DORPHON},
      {"DORPHON_ECLAIR", DORPHON_ECLAIR},
      {"DRAGON", DRAGON},
      {"DUBCHIC", DUBCHIC},
      {"DUBWITCH", DUBWITCH},
      {"EGG_RAPPY", EGG_RAPPY},
      {"EPSIGUARD", EPSIGUARD},
      {"EPSILON", EPSILON},
      {"EVIL_SHARK", EVIL_SHARK},
      {"GAEL", GAEL},
      {"GAL_GRYPHON", GAL_GRYPHON},
      {"GARANZ", GARANZ},
      {"GEE", GEE},
      {"GI_GUE", GI_GUE},
      {"GIBBLES", GIBBLES},
      {"GIGOBOOMA", GIGOBOOMA},
      {"GILLCHIC", GILLCHIC},
      {"GIRTABLULU", GIRTABLULU},
      {"GOBOOMA", GOBOOMA},
      {"GOL_DRAGON", GOL_DRAGON},
      {"GORAN", GORAN},
      {"GORAN_DETONATOR", GORAN_DETONATOR},
      {"GRASS_ASSASSIN", GRASS_ASSASSIN},
      {"GUIL_SHARK", GUIL_SHARK},
      {"HALLO_RAPPY", HALLO_RAPPY},
      {"HIDOOM", HIDOOM},
      {"HILDEBEAR", HILDEBEAR},
      {"HILDEBLUE", HILDEBLUE},
      {"ILL_GILL", ILL_GILL},
      {"KONDRIEU", KONDRIEU},
      {"LA_DIMENIAN", LA_DIMENIAN},
      {"LOVE_RAPPY", LOVE_RAPPY},
      {"MERICAROL", MERICAROL},
      {"MERICUS", MERICUS},
      {"MERIKLE", MERIKLE},
      {"MERILLIA", MERILLIA},
      {"MERILTAS", MERILTAS},
      {"MERISSA_A", MERISSA_A},
      {"MERISSA_AA", MERISSA_AA},
      {"MIGIUM", MIGIUM},
      {"MONEST", MONEST},
      {"MORFOS", MORFOS},
      {"MOTHMANT", MOTHMANT},
      {"NANO_DRAGON", NANO_DRAGON},
      {"NAR_LILY", NAR_LILY},
      {"OLGA_FLOW_1", OLGA_FLOW_1},
      {"OLGA_FLOW_2", OLGA_FLOW_2},
      {"PAL_SHARK", PAL_SHARK},
      {"PAN_ARMS", PAN_ARMS},
      {"PAZUZU", PAZUZU},
      {"PAZUZU_ALT", PAZUZU_ALT},
      {"PIG_RAY", PIG_RAY},
      {"POFUILLY_SLIME", POFUILLY_SLIME},
      {"POUILLY_SLIME", POUILLY_SLIME},
      {"POISON_LILY", POISON_LILY},
      {"PYRO_GORAN", PYRO_GORAN},
      {"RAG_RAPPY", RAG_RAPPY},
      {"RECOBOX", RECOBOX},
      {"RECON", RECON},
      {"SAINT_MILLION", SAINT_MILLION},
      {"SAINT_RAPPY", SAINT_RAPPY},
      {"SAND_RAPPY", SAND_RAPPY},
      {"SAND_RAPPY_ALT", SAND_RAPPY_ALT},
      {"SATELLITE_LIZARD", SATELLITE_LIZARD},
      {"SATELLITE_LIZARD_ALT", SATELLITE_LIZARD_ALT},
      {"SAVAGE_WOLF", SAVAGE_WOLF},
      {"SHAMBERTIN", SHAMBERTIN},
      {"SINOW_BEAT", SINOW_BEAT},
      {"SINOW_BERILL", SINOW_BERILL},
      {"SINOW_GOLD", SINOW_GOLD},
      {"SINOW_SPIGELL", SINOW_SPIGELL},
      {"SINOW_ZELE", SINOW_ZELE},
      {"SINOW_ZOA", SINOW_ZOA},
      {"SO_DIMENIAN", SO_DIMENIAN},
      {"UL_GIBBON", UL_GIBBON},
      {"VOL_OPT_1", VOL_OPT_1},
      {"VOL_OPT_2", VOL_OPT_2},
      {"VOL_OPT_AMP", VOL_OPT_AMP},
      {"VOL_OPT_CORE", VOL_OPT_CORE},
      {"VOL_OPT_MONITOR", VOL_OPT_MONITOR},
      {"VOL_OPT_PILLAR", VOL_OPT_PILLAR},
      {"YOWIE", YOWIE},
      {"YOWIE_ALT", YOWIE_ALT},
      {"ZE_BOOTA", ZE_BOOTA},
      {"ZOL_GIBBON", ZOL_GIBBON},
      {"ZU", ZU},
      {"ZU_ALT", ZU_ALT},
    };

    int numNames = sizeof(names) / sizeof(names[0]);

    for (int i = 0; i < numNames; i++) {
        if (strcmp(names[i].name, name) == 0) {
            return names[i].type;
        }
    }

    fprintf(stderr, "Error: Unknown enemy type %s\n", name);
    exit(1);
}

bool enemy_type_valid_for_episode(Episode episode, EnemyType enemy_type) {
    switch (episode) {
    case EP1:
        switch (enemy_type) {
        case MOTHMANT:
        case MONEST:
        case SAVAGE_WOLF:
        case BARBAROUS_WOLF:
        case POISON_LILY:
        case NAR_LILY:
        case SINOW_BEAT:
        case CANADINE:
        case CANADINE_GROUP:
        case CANANE:
        case CHAOS_SORCERER:
        case CHAOS_BRINGER:
        case DARK_BELRA:
        case DE_ROL_LE:
        case DRAGON:
        case SINOW_GOLD:
        case RAG_RAPPY:
        case AL_RAPPY:
        case NANO_DRAGON:
        case DUBCHIC:
        case GILLCHIC:
        case GARANZ:
        case DARK_GUNNER:
        case BULCLAW:
        case CLAW:
        case VOL_OPT_2:
        case POUILLY_SLIME:
        case POFUILLY_SLIME:
        case PAN_ARMS:
        case HIDOOM:
        case MIGIUM:
        case DARVANT:
        case DARVANT_ULTIMATE:
        case DARK_FALZ_1:
        case DARK_FALZ_2:
        case DARK_FALZ_3:
        case HILDEBEAR:
        case HILDEBLUE:
        case BOOMA:
        case GOBOOMA:
        case GIGOBOOMA:
        case GRASS_ASSASSIN:
        case EVIL_SHARK:
        case PAL_SHARK:
        case GUIL_SHARK:
        case DELSABER:
        case DIMENIAN:
        case LA_DIMENIAN:
        case SO_DIMENIAN:
            return true;
        default:
            return false;
        }
    case EP2:
        switch (enemy_type) {
        case MOTHMANT:
        case MONEST:
        case SAVAGE_WOLF:
        case BARBAROUS_WOLF:
        case POISON_LILY:
        case NAR_LILY:
        case SINOW_BERILL:
        case GEE:
        case CHAOS_SORCERER:
        case DELBITER:
        case DARK_BELRA:
        case BARBA_RAY:
        case GOL_DRAGON:
        case SINOW_SPIGELL:
        case RAG_RAPPY:
        case LOVE_RAPPY:
        case SAINT_RAPPY:
        case EGG_RAPPY:
        case HALLO_RAPPY:
        case GI_GUE:
        case DUBCHIC:
        case GILLCHIC:
        case GARANZ:
        case GAL_GRYPHON:
        case EPSILON:
        case DEL_LILY:
        case ILL_GILL:
        case OLGA_FLOW_1:
        case OLGA_FLOW_2:
        case GAEL:
        case DELDEPTH:
        case PAN_ARMS:
        case HIDOOM:
        case MIGIUM:
        case MERICAROL:
        case UL_GIBBON:
        case ZOL_GIBBON:
        case GIBBLES:
        case MORFOS:
        case RECOBOX:
        case RECON:
        case SINOW_ZOA:
        case SINOW_ZELE:
        case MERIKLE:
        case MERICUS:
        case HILDEBEAR:
        case HILDEBLUE:
        case MERILLIA:
        case MERILTAS:
        case GRASS_ASSASSIN:
        case DOLMOLM:
        case DOLMDARL:
        case DELSABER:
        case DIMENIAN:
        case LA_DIMENIAN:
        case SO_DIMENIAN:
            return true;
        default:
            return false;
        }
    case EP4:
        switch (enemy_type) {
        case BOOTA:
        case ZE_BOOTA:
        case BA_BOOTA:
        case SAND_RAPPY:
        case DEL_RAPPY:
        case ZU:
        case PAZUZU:
        case ASTARK:
        case SATELLITE_LIZARD:
        case YOWIE:
        case DORPHON:
        case DORPHON_ECLAIR:
        case GORAN:
        case PYRO_GORAN:
        case GORAN_DETONATOR:
        case SAND_RAPPY_ALT:
        case DEL_RAPPY_ALT:
        case MERISSA_A:
        case MERISSA_AA:
        case ZU_ALT:
        case PAZUZU_ALT:
        case SATELLITE_LIZARD_ALT:
        case YOWIE_ALT:
        case GIRTABLULU:
        case SAINT_MILLION:
        case SHAMBERTIN:
        case KONDRIEU:
            return true;
        default:
            return false;
        }
    default:
        return false;
    }
}

uint8_t battle_param_index_for_enemy_type(Episode episode, EnemyType enemy_type) {
    switch (episode) {
    case EP1:
        switch (enemy_type) {
        case MOTHMANT:
            return 0x00;
        case MONEST:
            return 0x01;
        case SAVAGE_WOLF:
            return 0x02;
        case BARBAROUS_WOLF:
            return 0x03;
        case POISON_LILY:
            return 0x04;
        case NAR_LILY:
            return 0x05;
        case SINOW_BEAT:
            return 0x06;
        case CANADINE:
            return 0x07;
        case CANADINE_GROUP:
            return 0x08;
        case CANANE:
            return 0x09;
        case CHAOS_SORCERER:
            return 0x0A;
        case CHAOS_BRINGER:
            return 0x0D;
        case DARK_BELRA:
            return 0x0E;
        case DE_ROL_LE:
            return 0x0F;
        case DRAGON:
            return 0x12;
        case SINOW_GOLD:
            return 0x13;
        case RAG_RAPPY:
            return 0x18;
        case AL_RAPPY:
            return 0x19;
        case NANO_DRAGON:
            return 0x1A;
        case DUBCHIC:
            return 0x1B;
        case GILLCHIC:
            return 0x1C;
        case GARANZ:
            return 0x1D;
        case DARK_GUNNER:
            return 0x1E;
        case BULCLAW:
            return 0x1F;
        case CLAW:
            return 0x20;
        case VOL_OPT_2:
            return 0x25;
        case POUILLY_SLIME:
            return 0x2F;
        case POFUILLY_SLIME:
            return 0x30;
        case PAN_ARMS:
            return 0x31;
        case HIDOOM:
            return 0x32;
        case MIGIUM:
            return 0x33;
        case DARVANT:
            return 0x35;
        case DARVANT_ULTIMATE:
            return 0x39;
        case DARK_FALZ_1:
            return 0x36;
        case DARK_FALZ_2:
            return 0x37;
        case DARK_FALZ_3:
            return 0x38;
        case HILDEBEAR:
            return 0x49;
        case HILDEBLUE:
            return 0x4A;
        case BOOMA:
            return 0x4B;
        case GOBOOMA:
            return 0x4C;
        case GIGOBOOMA:
            return 0x4D;
        case GRASS_ASSASSIN:
            return 0x4E;
        case EVIL_SHARK:
            return 0x4F;
        case PAL_SHARK:
            return 0x50;
        case GUIL_SHARK:
            return 0x51;
        case DELSABER:
            return 0x52;
        case DIMENIAN:
            return 0x53;
        case LA_DIMENIAN:
            return 0x54;
        case SO_DIMENIAN:
            return 0x55;
        default:
            ERR_LOG(string_printf("%s does not have battle parameters in Episode 1", enum_for_name(enemy_type)));
            return 0xFF; // 返回一个特殊值表示无效参数
        }
        break;
    case EP2:
        switch (enemy_type) {
        case MOTHMANT:
            return 0x00;
        case MONEST:
            return 0x01;
        case SAVAGE_WOLF:
            return 0x02;
        case BARBAROUS_WOLF:
            return 0x03;
        case POISON_LILY:
            return 0x04;
        case NAR_LILY:
            return 0x05;
        case SINOW_BERILL:
            return 0x06;
        case GEE:
            return 0x07;
        case CHAOS_SORCERER:
            return 0x0A;
        case DELBITER:
            return 0x0D;
        case DARK_BELRA:
            return 0x0E;
        case BARBA_RAY:
            return 0x0F;
        case GOL_DRAGON:
            return 0x12;
        case SINOW_SPIGELL:
            return 0x13;
        case RAG_RAPPY:
            return 0x18;
        case LOVE_RAPPY:
        case SAINT_RAPPY:
        case EGG_RAPPY:
        case HALLO_RAPPY:
            return 0x19;
        case GI_GUE:
            return 0x1A;
        case DUBCHIC:
            return 0x1B;
        case GILLCHIC:
            return 0x1C;
        case GARANZ:
            return 0x1D;
        case GAL_GRYPHON:
            return 0x1E;
        case EPSILON:
            return 0x23;
        case DEL_LILY:
            return 0x25;
        case ILL_GILL:
            return 0x26;
        case OLGA_FLOW_1:
            return 0x2B;
        case OLGA_FLOW_2:
            return 0x2C;
        case GAEL:
            return 0x2E;
        case DELDEPTH:
            return 0x30;
        case PAN_ARMS:
            return 0x31;
        case HIDOOM:
            return 0x32;
        case MIGIUM:
            return 0x33;
        case MERICAROL:
            return 0x3A;
        case UL_GIBBON:
            return 0x3B;
        case ZOL_GIBBON:
            return 0x3C;
        case GIBBLES:
            return 0x3D;
        case MORFOS:
            return 0x40;
        case RECOBOX:
            return 0x41;
        case RECON:
            return 0x42;
        case SINOW_ZOA:
            return 0x43;
        case SINOW_ZELE:
            return 0x44;
        case MERIKLE:
            return 0x45;
        case MERICUS:
            return 0x46;
        case HILDEBEAR:
            return 0x49;
        case HILDEBLUE:
            return 0x4A;
        case MERILLIA:
            return 0x4B;
        case MERILTAS:
            return 0x4C;
        case GRASS_ASSASSIN:
            return 0x4E;
        case DOLMOLM:
            return 0x4F;
        case DOLMDARL:
            return 0x50;
        case DELSABER:
            return 0x52;
        case DIMENIAN:
            return 0x53;
        case LA_DIMENIAN:
            return 0x54;
        case SO_DIMENIAN:
            return 0x55;
        default:
            ERR_LOG(string_printf("%s does not have battle parameters in Episode 2", enum_for_name(enemy_type)));
            return 0xFF; // 返回一个特殊值表示无效参数
        }
        break;
    case EP4:
        switch (enemy_type) {
        case BOOTA:
            return 0x00;
        case ZE_BOOTA:
            return 0x01;
        case BA_BOOTA:
            return 0x03;
        case SAND_RAPPY:
            return 0x05;
        case DEL_RAPPY:
            return 0x06;
        case ZU:
            return 0x07;
        case PAZUZU:
            return 0x08;
        case ASTARK:
            return 0x09;
        case SATELLITE_LIZARD:
            return 0x0D;
        case YOWIE:
            return 0x0E;
        case DORPHON:
            return 0x0F;
        case DORPHON_ECLAIR:
            return 0x10;
        case GORAN:
            return 0x11;
        case PYRO_GORAN:
            return 0x12;
        case GORAN_DETONATOR:
            return 0x13;
        case SAND_RAPPY_ALT:
            return 0x17;
        case DEL_RAPPY_ALT:
            return 0x18;
        case MERISSA_A:
            return 0x19;
        case MERISSA_AA:
            return 0x1A;
        case ZU_ALT:
            return 0x1B;
        case PAZUZU_ALT:
            return 0x1C;
        case SATELLITE_LIZARD_ALT:
            return 0x1D;
        case YOWIE_ALT:
            return 0x1E;
        case GIRTABLULU:
            return 0x1F;
        case SAINT_MILLION:
        case SHAMBERTIN:
        case KONDRIEU:
            return 0x22;
        default:
            ERR_LOG(string_printf("%s does not have battle parameters in Episode 4", enum_for_name(enemy_type)));
            return 0xFF; // 返回一个特殊值表示无效参数
        }
        break;
    default:
        ERR_LOG("incorrect episode in battle param lookup");
        return 0xFF; // 返回一个特殊值表示无效参数
    }
    ERR_LOG("fallthrough case in battle param lookup");
}

uint8_t rare_table_index_for_enemy_type(EnemyType enemy_type) {
    switch (enemy_type) {
    case AL_RAPPY:
        return 0x06;
    case ASTARK:
        return 0x01;
    case BA_BOOTA:
        return 0x0B;
    case BARBA_RAY:
        return 0x49;
    case BARBAROUS_WOLF:
        return 0x08;
    case BOOMA:
        return 0x09;
    case BOOTA:
        return 0x09;
    case BULCLAW:
        return 0x28;
    case CANADINE:
    case CANADINE_GROUP:
        return 0x1C;
    case CANANE:
        return 0x1D;
    case CHAOS_BRINGER:
        return 0x24;
    case CHAOS_SORCERER:
        return 0x1F;
    case CLAW:
        return 0x26;
    case DARK_BELRA:
        return 0x25;
    case DARK_FALZ_2:
        return 0x2F;
    case DARK_FALZ_3:
        return 0x2F;
    case DARK_GUNNER:
        return 0x22;
    case DE_ROL_LE:
        return 0x2D;
    case DEL_LILY:
        return 0x53;
    case DEL_RAPPY:
    case DEL_RAPPY_ALT:
        return 0x12;
    case DELBITER:
        return 0x48;
    case DELDEPTH:
        return 0x47;
    case DELSABER:
        return 0x1E;
    case DIMENIAN:
        return 0x29;
    case DOLMDARL:
        return 0x41;
    case DOLMOLM:
        return 0x40;
    case DORPHON:
        return 0x0C;
    case DORPHON_ECLAIR:
        return 0x0D;
    case DRAGON:
        return 0x2C;
    case DUBCHIC:
        return 0x18;
    case EGG_RAPPY:
        return 0x51;
    case EPSILON:
        return 0x54;
    case EVIL_SHARK:
        return 0x10;
    case GAL_GRYPHON:
        return 0x4D;
    case GARANZ:
        return 0x19;
    case GEE:
        return 0x36;
    case GI_GUE:
        return 0x37;
    case GIBBLES:
        return 0x3D;
    case GIGOBOOMA:
        return 0x0B;
    case GILLCHIC:
        return 0x32;
    case GIRTABLULU:
        return 0x06;
    case GOBOOMA:
        return 0x0A;
    case GOL_DRAGON:
        return 0x4C;
    case GORAN:
        return 0x0E;
    case GORAN_DETONATOR:
        return 0x0F;
    case GRASS_ASSASSIN:
        return 0x0C;
    case GUIL_SHARK:
        return 0x12;
    case HALLO_RAPPY:
        return 0x50;
    case HIDOOM:
        return 0x17;
    case HILDEBEAR:
        return 0x01;
    case HILDEBLUE:
        return 0x02;
    case ILL_GILL:
        return 0x52;
    case KONDRIEU:
        return 0x15;
    case LA_DIMENIAN:
        return 0x2A;
    case LOVE_RAPPY:
        return 0x33;
    case MERICAROL:
        return 0x38;
    case MERICUS:
        return 0x3A;
    case MERIKLE:
        return 0x39;
    case MERILLIA:
        return 0x34;
    case MERILTAS:
        return 0x35;
    case MERISSA_A:
        return 0x04;
    case MERISSA_AA:
        return 0x05;
    case MIGIUM:
        return 0x16;
    case MONEST:
        return 0x04;
    case MORFOS:
        return 0x42;
    case MOTHMANT:
        return 0x03;
    case NANO_DRAGON:
        return 0x0F;
    case NAR_LILY:
        return 0x0E;
    case OLGA_FLOW_2:
        return 0x4E;
    case PAL_SHARK:
        return 0x11;
    case PAN_ARMS:
        return 0x15;
    case PAZUZU:
    case PAZUZU_ALT:
        return 0x08;
    case POFUILLY_SLIME:
        return 0x13;
    case POUILLY_SLIME:
        return 0x14;
    case POISON_LILY:
        return 0x0D;
    case PYRO_GORAN:
        return 0x10;
    case RAG_RAPPY:
        return 0x05;
    case RECOBOX:
        return 0x43;
    case RECON:
        return 0x44;
    case SAINT_RAPPY:
        return 0x4F;
    case SAINT_MILLION:
        return 0x13;
    case SAND_RAPPY:
    case SAND_RAPPY_ALT:
        return 0x11;
    case SATELLITE_LIZARD:
    case SATELLITE_LIZARD_ALT:
        return 0x03;
    case SAVAGE_WOLF:
        return 0x07;
    case SHAMBERTIN:
        return 0x14;
    case SINOW_BEAT:
        return 0x1A;
    case SINOW_BERILL:
        return 0x3E;
    case SINOW_GOLD:
        return 0x1B;
    case SINOW_SPIGELL:
        return 0x3F;
    case SINOW_ZELE:
        return 0x46;
    case SINOW_ZOA:
        return 0x45;
    case SO_DIMENIAN:
        return 0x2B;
    case UL_GIBBON:
        return 0x3B;
    case VOL_OPT_2:
        return 0x2E;
    case YOWIE:
    case YOWIE_ALT:
        return 0x02;
    case ZE_BOOTA:
        return 0x0A;
    case ZOL_GIBBON:
        return 0x3C;
    case ZU:
    case ZU_ALT:
        return 0x07;
    default:
        ERR_LOG(string_printf("%s does not have a rare table entry", enum_for_name(enemy_type)));
        return -1;
    }
}

