/*
    梦幻之星中国 舰船服务器 物品数据
    版权 (C) 2022, 2023 Sancaros

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License version 3
    as published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef PSOCN_ITEM_LIST_H
#define PSOCN_ITEM_LIST_H

#include <stdio.h>
#include <stdint.h>

#ifndef _WIN32
#define PACKED __attribute__((packed))
#else
#define PACKED __declspec(align(1))
#pragma pack(push, 1) 
#endif

#pragma warning (disable:4819)
/* 物品代码清单. */
typedef enum item_code_e {
    Item_Saber = 0x000100,
    Item_Brand = 0x010100,
    Item_Buster = 0x020100,
    Item_Pallasch = 0x030100,
    Item_Gladius = 0x040100,
    Item_DBS_SABER = 0x050100,
    Item_KALADBOLG = 0x060100,
    Item_DURANDAL = 0x070100,
    Item_Sword = 0x000200,
    Item_Gigush = 0x010200,
    Item_Breaker = 0x020200,
    Item_Claymore = 0x030200,
    Item_Calibur = 0x040200,
    Item_FLOWENS_SWORD = 0x050200,
    Item_LAST_SURVIVOR = 0x060200,
    Item_DRAGON_SLAYER = 0x070200,
    Item_Dagger = 0x000300,
    Item_Knife = 0x010300,
    Item_Blade = 0x020300,
    Item_Edge = 0x030300,
    Item_Ripper = 0x040300,
    Item_BLADE_DANCE = 0x050300,
    Item_BLOODY_ART = 0x060300,
    Item_CROSS_SCAR = 0x070300,
    Item_Partisan = 0x000400,
    Item_Halbert = 0x010400,
    Item_Glaive = 0x020400,
    Item_Berdys = 0x030400,
    Item_Gungnir = 0x040400,
    Item_BRIONAC = 0x050400,
    Item_VJAYA = 0x060400,
    Item_GAE_BOLG = 0x070400,
    Item_Slicer = 0x000500,
    Item_Spinner = 0x010500,
    Item_Cutter = 0x020500,
    Item_Sawcer = 0x030500,
    Item_Diska = 0x040500,
    Item_SLICER_OF_ASSASSIN = 0x050500,
    Item_DISKA_OF_LIBERATOR = 0x060500,
    Item_DISKA_OF_BRAVEMAN = 0x070500,
    Item_Handgun = 0x000600,
    Item_Autogun = 0x010600,
    Item_Lockgun = 0x020600,
    Item_Railgun = 0x030600,
    Item_Raygun = 0x040600,
    Item_VARISTA = 0x050600,
    Item_CUSTOM_RAY_ver_OO = 0x060600,
    Item_BRAVACE = 0x070600,
    Item_Rifle = 0x000700,
    Item_Sniper = 0x010700,
    Item_Blaster = 0x020700,
    Item_Beam = 0x030700,
    Item_Laser = 0x040700,
    Item_VISK_235W = 0x050700,
    Item_WALS_MK2 = 0x060700,
    Item_JUSTY_23ST = 0x070700,
    Item_Mechgun = 0x000800,
    Item_Assault = 0x010800,
    Item_Repeater = 0x020800,
    Item_Gatling = 0x030800,
    Item_Vulcan = 0x040800,
    Item_M_and_A60_VISE = 0x050800,
    Item_H_and_S25_JUSTICE = 0x060800,
    Item_L_and_K14_COMBAT = 0x070800,
    Item_Shot = 0x000900,
    Item_Spread = 0x010900,
    Item_Cannon = 0x020900,
    Item_Launcher = 0x030900,
    Item_Arms = 0x040900,
    Item_CRUSH_BULLET = 0x050900,
    Item_METEOR_SMASH = 0x060900,
    Item_FINAL_IMPACT = 0x070900,
    Item_Cane = 0x000A00,
    Item_Stick = 0x010A00,
    Item_Mace = 0x020A00,
    Item_Club = 0x030A00,
    Item_CLUB_OF_LACONIUM = 0x040A00,
    Item_MACE_OF_ADAMAN = 0x050A00,
    Item_CLUB_OF_ZUMIURAN = 0x060A00,
    Item_Rod = 0x000B00,
    Item_Pole = 0x010B00,
    Item_Pillar = 0x020B00,
    Item_Striker = 0x030B00,
    Item_BATTLE_VERGE = 0x040B00,
    Item_BRAVE_HAMMER = 0x050B00,
    Item_ALIVE_AQHU = 0x060B00,
    Item_Wand = 0x000C00,
    Item_Staff = 0x010C00,
    Item_Baton = 0x020C00,
    Item_Scepter = 0x030C00,
    Item_FIRE_SCEPTER_AGNI = 0x040C00,
    Item_ICE_STAFF_DAGON = 0x050C00,
    Item_STORM_WAND_INDRA = 0x060C00,
    Item_PHOTON_CLAW = 0x000D00,
    Item_SILENCE_CLAW = 0x010D00,
    Item_NEIS_CLAW = 0x020D00,
    Item_DOUBLE_SABER = 0x000E00,
    Item_STAG_CUTLERY = 0x010E00,
    Item_TWIN_BRAND = 0x020E00,
    Item_BRAVE_KNUCKLE = 0x000F00,
    Item_ANGRY_FIST = 0x010F00,
    Item_GOD_HAND = 0x020F00,
    Item_SONIC_KNUCKLE = 0x030F00,
    Item_OROTIAGITO_alt = 0x040F00,   /* Why twice? */
    Item_OROTIAGITO = 0x001000,
    Item_AGITO_1975 = 0x011000,
    Item_AGITO_1983 = 0x021000,
    Item_AGITO_2001 = 0x031000,
    Item_AGITO_1991 = 0x041000,
    Item_AGITO_1977 = 0x051000,
    Item_AGITO_1980 = 0x061000,
    Item_SOUL_EATER = 0x001100,
    Item_SOUL_BANISH = 0x011100,
    Item_SPREAD_NEEDLE = 0x001200,
    Item_HOLY_RAY = 0x001300,
    Item_INFERNO_BAZOOKA = 0x001400,
    Item_FLAME_VISIT = 0x001500,
    Item_AKIKOS_FRYING_PAN = 0x001600,
    Item_C_SORCERERS_CANE = 0x001700,
    Item_S_BEATS_BLADE = 0x001800,
    Item_P_ARMSS_BLADE = 0x001900,
    Item_DELSABERS_BUSTER = 0x001A00,
    Item_C_BRINGERS_RIFLE = 0x001B00,
    Item_EGG_BLASTER = 0x001C00,
    Item_PSYCHO_WAND = 0x001D00,
    Item_HEAVEN_PUNISHER = 0x001E00,
    Item_LAVIS_CANNON = 0x001F00,
    Item_VICTOR_AXE = 0x002000,
    Item_CHAIN_SAWD = 0x002100,
    Item_CADUCEUS = 0x002200,
    Item_STING_TIP = 0x002300,
    Item_MAGICAL_PIECE = 0x002400,
    Item_TECHNICAL_CROZIER = 0x002500,
    Item_SUPPRESSED_GUN = 0x002600,
    Item_ANCIENT_SABER = 0x002700,
    Item_HARISEN_BATTLE_FAN = 0x002800,
    Item_YAMIGARASU = 0x002900,
    Item_AKIKOS_WOK = 0x002A00,
    Item_TOY_HAMMER = 0x002B00,
    Item_ELYSION = 0x002C00,
    Item_RED_SABER = 0x002D00,
    Item_METEOR_CUDGEL = 0x002E00,
    Item_MONKEY_KING_BAR = 0x002F00,
    Item_DOUBLE_CANNON = 0x003000,
    Item_HUGE_BATTLE_FAN = 0x003100,
    Item_TSUMIKIRI_J_SWORD = 0x003200,
    Item_SEALED_J_SWORD = 0x003300,
    Item_RED_SWORD = 0x003400,
    Item_CRAZY_TUNE = 0x003500,
    Item_TWIN_CHAKRAM = 0x003600,
    Item_WOK_OF_AKIKOS_SHOP = 0x003700,
    Item_LAVIS_BLADE = 0x003800,
    Item_RED_DAGGER = 0x003900,
    Item_MADAMS_PARASOL = 0x003A00,
    Item_MADAMS_UMBRELLA = 0x003B00,
    Item_IMPERIAL_PICK = 0x003C00,
    Item_BERDYSH = 0x003D00,
    Item_RED_PARTISAN = 0x003E00,
    Item_FLIGHT_CUTTER = 0x003F00,
    Item_FLIGHT_FAN = 0x004000,
    Item_RED_SLICER = 0x004100,
    Item_HANDGUN_GULD = 0x004200,
    Item_HANDGUN_MILLA = 0x004300,
    Item_RED_HANDGUN = 0x004400,
    Item_FROZEN_SHOOTER = 0x004500,
    Item_ANTI_ANDROID_RIFLE = 0x004600,
    Item_ROCKET_PUNCH = 0x004700,
    Item_SAMBA_MARACAS = 0x004800,
    Item_TWIN_PSYCHOGUN = 0x004900,
    Item_DRILL_LAUNCHER = 0x004A00,
    Item_GULD_MILLA = 0x004B00,
    Item_RED_MECHGUN = 0x004C00,
    Item_BERLA_CANNON = 0x004D00,
    Item_PANZER_FAUST = 0x004E00,
    Item_SUMMIT_MOON = 0x004F00,
    Item_WINDMILL = 0x005000,
    Item_EVIL_CURST = 0x005100,
    Item_FLOWER_CANE = 0x005200,
    Item_HILDEBEARS_CANE = 0x005300,
    Item_HILDEBLUES_CANE = 0x005400,
    Item_RABBIT_WAND = 0x005500,
    Item_PLANTAIN_LEAF = 0x005600,
    Item_DEMONIC_FORK = 0x005700,
    Item_STRIKER_OF_CHAO = 0x005800,
    Item_BROOM = 0x005900,
    Item_PROPHETS_OF_MOTAV = 0x005A00,
    Item_THE_SIGH_OF_A_GOD = 0x005B00,
    Item_TWINKLE_STAR = 0x005C00,
    Item_PLANTAIN_FAN = 0x005D00,
    Item_TWIN_BLAZE = 0x005E00,
    Item_MARINAS_BAG = 0x005F00,
    Item_DRAGONS_CLAW = 0x006000,
    Item_PANTHERS_CLAW = 0x006100,
    Item_S_REDS_BLADE = 0x006200,
    Item_PLANTAIN_HUGE_FAN = 0x006300,
    Item_CHAMELEON_SCYTHE = 0x006400,
    Item_YASMINKOV_3000R = 0x006500,
    Item_ANO_RIFLE = 0x006600,
    Item_BARANZ_LAUNCHER = 0x006700,
    Item_BRANCH_OF_PAKUPAKU = 0x006800,
    Item_HEART_OF_POUMN = 0x006900,
    Item_YASMINKOV_2000H = 0x006A00,
    Item_YASMINKOV_7000V = 0x006B00,
    Item_YASMINKOV_9200M = 0x006C00,
    Item_MASER_BEAM = 0x006D00,
    Item_GAME_MAGAZNE = 0x006E00,
    Item_FLOWER_BOUQUET = 0x006F00,
    Item_SRANK_SABER = 0x007000,
    Item_SRANK_SWORD = 0x007100,
    Item_SRANK_BLADE = 0x007200,
    Item_SRANK_PARTISAN = 0x007300,
    Item_SRANK_SLICER = 0x007400,
    Item_SRANK_GUN = 0x007500,
    Item_SRANK_RIFLE = 0x007600,
    Item_SRANK_MECHGUN = 0x007700,
    Item_SRANK_SHOT = 0x007800,
    Item_SRANK_CANE = 0x007900,
    Item_SRANK_ROD = 0x007A00,
    Item_SRANK_WAND = 0x007B00,
    Item_SRANK_TWIN = 0x007C00,
    Item_SRANK_CLAW = 0x007D00,
    Item_SRANK_BAZOOKA = 0x007E00,
    Item_SRANK_NEEDLE = 0x007F00,
    Item_SRANK_SCYTHE = 0x008000,
    Item_SRANK_HAMMER = 0x008100,
    Item_SRANK_MOON = 0x008200,
    Item_SRANK_PSYCHOGUN = 0x008300,
    Item_SRANK_PUNCH = 0x008400,
    Item_SRANK_WINDMILL = 0x008500,
    Item_SRANK_HARISEN = 0x008600,
    Item_SRANK_J_BLADE = 0x008700,
    Item_SRANK_J_CUTTER = 0x008800,
    Item_Frame = 0x000101,
    Item_Armor = 0x010101,
    Item_Psy_Armor = 0x020101,
    Item_Giga_Frame = 0x030101,
    Item_Soul_Frame = 0x040101,
    Item_Cross_Armor = 0x050101,
    Item_Solid_Frame = 0x060101,
    Item_Brave_Armor = 0x070101,
    Item_Hyper_Frame = 0x080101,
    Item_Grand_Armor = 0x090101,
    Item_Shock_Frame = 0x0A0101,
    Item_Kings_Frame = 0x0B0101,
    Item_Dragon_Frame = 0x0C0101,
    Item_Absorb_Armor = 0x0D0101,
    Item_Protect_Frame = 0x0E0101,
    Item_General_Armor = 0x0F0101,
    Item_Perfect_Frame = 0x100101,
    Item_Valiant_Frame = 0x110101,
    Item_Imperial_Armor = 0x120101,
    Item_Holiness_Armor = 0x130101,
    Item_Guardian_Armor = 0x140101,
    Item_Divinity_Armor = 0x150101,
    Item_Ultimate_Frame = 0x160101,
    Item_Celestial_Armor = 0x170101,
    Item_HUNTER_FIELD = 0x180101,
    Item_RANGER_FIELD = 0x190101,
    Item_FORCE_FIELD = 0x1A0101,
    Item_REVIVAL_GARMENT = 0x1B0101,
    Item_SPIRIT_GARMENT = 0x1C0101,
    Item_STINK_FRAME = 0x1D0101,
    Item_D_PARTS_ver1_01 = 0x1E0101,
    Item_D_PARTS_ver2_10 = 0x1F0101,
    Item_PARASITE_WEAR_De_Rol = 0x200101,
    Item_PARASITE_WEAR_Nelgal = 0x210101,
    Item_PARASITE_WEAR_Vajulla = 0x220101,
    Item_SENSE_PLATE = 0x230101,
    Item_GRAVITON_PLATE = 0x240101,
    Item_ATTRIBUTE_PLATE = 0x250101,
    Item_FLOWENS_FRAME = 0x260101,
    Item_CUSTOM_FRAME_ver_OO = 0x270101,
    Item_DBS_ARMOR = 0x280101,
    Item_GUARD_WAVE = 0x290101,
    Item_DF_FIELD = 0x2A0101,
    Item_LUMINOUS_FIELD = 0x2B0101,
    Item_CHU_CHU_FEVER = 0x2C0101,
    Item_LOVE_HEART = 0x2D0101,
    Item_FLAME_GARMENT = 0x2E0101,
    Item_VIRUS_ARMOR_Lafuteria = 0x2F0101,
    Item_BRIGHTNESS_CIRCLE = 0x300101,
    Item_AURA_FIELD = 0x310101,
    Item_ELECTRO_FRAME = 0x320101,
    Item_SACRED_CLOTH = 0x330101,
    Item_SMOKING_PLATE = 0x340101,
    Item_Barrier = 0x000201,
    Item_Shield = 0x010201,
    Item_Core_Shield = 0x020201,
    Item_Giga_Shield = 0x030201,
    Item_Soul_Barrier = 0x040201,
    Item_Hard_Shield = 0x050201,
    Item_Brave_Barrier = 0x060201,
    Item_Solid_Shield = 0x070201,
    Item_Flame_Barrier = 0x080201,
    Item_Plasma_Barrier = 0x090201,
    Item_Freeze_Barrier = 0x0A0201,
    Item_Psychic_Barrier = 0x0B0201,
    Item_General_Shield = 0x0C0201,
    Item_Protect_Barrier = 0x0D0201,
    Item_Glorious_Shield = 0x0E0201,
    Item_Imperial_Barrier = 0x0F0201,
    Item_Guardian_Shield = 0x100201,
    Item_Divinity_Barrier = 0x110201,
    Item_Ultimate_Shield = 0x120201,
    Item_Spiritual_Shield = 0x130201,
    Item_Celestial_Shield = 0x140201,
    Item_INVISIBLE_GUARD = 0x150201,
    Item_SACRED_GUARD = 0x160201,
    Item_S_PARTS_ver1_16 = 0x170201,
    Item_S_PARTS_ver2_01 = 0x180201,
    Item_LIGHT_RELIEF = 0x190201,
    Item_SHIELD_OF_DELSABER = 0x1A0201,
    Item_FORCE_WALL = 0x1B0201,
    Item_RANGER_WALL = 0x1C0201,
    Item_HUNTER_WALL = 0x1D0201,
    Item_ATTRIBUTE_WALL = 0x1E0201,
    Item_SECRET_GEAR = 0x1F0201,
    Item_COMBAT_GEAR = 0x200201,
    Item_PROTO_REGENE_GEAR = 0x210201,
    Item_REGENERATE_GEAR = 0x220201,
    Item_REGENE_GEAR_ADV = 0x230201,
    Item_FLOWENS_SHIELD = 0x240201,
    Item_CUSTOM_BARRIER_ver_OO = 0x250201,
    Item_DBS_SHIELD = 0x260201,
    Item_RED_RING = 0x270201,
    Item_TRIPOLIC_SHIELD = 0x280201,
    Item_STANDSTILL_SHIELD = 0x290201,
    Item_SAFETY_HEART = 0x2A0201,
    Item_KASAMI_BRACER = 0x2B0201,
    Item_GODS_SHIELD_SUZAKU = 0x2C0201,
    Item_GODS_SHIELD_GENBU = 0x2D0201,
    Item_GODS_SHIELD_BYAKKO = 0x2E0201,
    Item_GODS_SHIELD_SEIRYU = 0x2F0201,
    Item_HANTERS_SHELL = 0x300201,
    Item_RIKOS_GLASSES = 0x310201,
    Item_RIKOS_EARRING = 0x320201,
    Item_BLUE_RING = 0x330201,
    Item_YELLOW_RING = 0x340201,
    Item_SECURE_FEET = 0x350201,
    Item_PURPLE_RING = 0x360201,
    Item_GREEN_RING = 0x370201,
    Item_BLACK_RING = 0x380201,
    Item_WHITE_RING = 0x390201,
    Item_Knight_Power = 0x000301,
    Item_General_Power = 0x010301,
    Item_Ogre_Power = 0x020301,
    Item_God_Power = 0x030301,
    Item_Priest_Mind = 0x040301,
    Item_General_Mind = 0x050301,
    Item_Angel_Mind = 0x060301,
    Item_God_Mind = 0x070301,
    Item_Marksman_Arm = 0x080301,
    Item_General_Arm = 0x090301,
    Item_Elf_Arm = 0x0A0301,
    Item_God_Arm = 0x0B0301,
    Item_Thief_Legs = 0x0C0301,
    Item_General_Legs = 0x0D0301,
    Item_Elf_Legs = 0x0E0301,
    Item_God_Legs = 0x0F0301,
    Item_Digger_HP = 0x100301,
    Item_General_HP = 0x110301,
    Item_Dragon_HP = 0x120301,
    Item_God_HP = 0x130301,
    Item_Magician_TP = 0x140301,
    Item_General_TP = 0x150301,
    Item_Angel_TP = 0x160301,
    Item_God_TP = 0x170301,
    Item_Warrior_Body = 0x180301,
    Item_General_Body = 0x190301,
    Item_Metal_Body = 0x1A0301,
    Item_God_Body = 0x1B0301,
    Item_Angel_Luck = 0x1C0301,
    Item_God_Luck = 0x1D0301,
    Item_Master_Ability = 0x1E0301,
    Item_Hero_Ability = 0x1F0301,
    Item_God_Ability = 0x200301,
    Item_Resist_Fire = 0x210301,
    Item_Resist_Flame = 0x220301,
    Item_Resist_Burning = 0x230301,
    Item_Resist_Cold = 0x240301,
    Item_Resist_Freeze = 0x250301,
    Item_Resist_Blizzard = 0x260301,
    Item_Resist_Shock = 0x270301,
    Item_Resist_Thunder = 0x280301,
    Item_Resist_Storm = 0x290301,
    Item_Resist_Light = 0x2A0301,
    Item_Resist_Saint = 0x2B0301,
    Item_Resist_Holy = 0x2C0301,
    Item_Resist_Dark = 0x2D0301,
    Item_Resist_Evil = 0x2E0301,
    Item_Resist_Devil = 0x2F0301,
    Item_All_Resist = 0x300301,
    Item_Super_Resist = 0x310301,
    Item_Perfect_Resist = 0x320301,
    Item_HP_Restorate = 0x330301,
    Item_HP_Generate = 0x340301,
    Item_HP_Revival = 0x350301,
    Item_TP_Restorate = 0x360301,
    Item_TP_Generate = 0x370301,
    Item_TP_Revival = 0x380301,
    Item_PB_Amplifier = 0x390301,
    Item_PB_Generate = 0x3A0301,
    Item_PB_Create = 0x3B0301,
    Item_Wizard_Technique = 0x3C0301,
    Item_Devil_Technique = 0x3D0301,
    Item_God_Technique = 0x3E0301,
    Item_General_Battle = 0x3F0301,
    Item_Devil_Battle = 0x400301,
    Item_God_Battle = 0x410301,
    Item_State_Maintenance = 0x420301,
    Item_Trap_Search = 0x430301,
    Item_Mag = 0x000002,
    Item_Varuna = 0x000102,
    Item_Mitra = 0x000202,
    Item_Surya = 0x000302,
    Item_Vayu = 0x000402,
    Item_Varaha = 0x000502,
    Item_Kama = 0x000602,
    Item_Ushasu = 0x000702,
    Item_Apsaras = 0x000802,
    Item_Kumara = 0x000902,
    Item_Kaitabha = 0x000A02,
    Item_Tapas = 0x000B02,
    Item_Bhirava = 0x000C02,
    Item_Kalki = 0x000D02,
    Item_Rudra = 0x000E02,
    Item_Marutah = 0x000F02,
    Item_Yaksa = 0x001002,
    Item_Sita = 0x001102,
    Item_Garuda = 0x001202,
    Item_Nandin = 0x001302,
    Item_Ashvinau = 0x001402,
    Item_Ribhava = 0x001502,
    Item_Soma = 0x001602,
    Item_Ila = 0x001702,
    Item_Durga = 0x001802,
    Item_Vritra = 0x001902,
    Item_Namuci = 0x001A02,
    Item_Sumba = 0x001B02,
    Item_Naga = 0x001C02,
    Item_Pitri = 0x001D02,
    Item_Kabanda = 0x001E02,
    Item_Ravana = 0x001F02,
    Item_Marica = 0x002002,
    Item_Soniti = 0x002102,
    Item_Preta = 0x002202,
    Item_Andhaka = 0x002302,
    Item_Bana = 0x002402,
    Item_Naraka = 0x002502,
    Item_Madhu = 0x002602,
    Item_Churel = 0x002702,
    Item_ROBOCHAO = 0x002802,
    Item_OPA_OPA = 0x002902,
    Item_PIAN = 0x002A02,
    Item_CHAO = 0x002B02,
    Item_CHU_CHU = 0x002C02,
    Item_KAPU_KAPU = 0x002D02,
    Item_ANGELS_WING = 0x002E02,
    Item_DEVILS_WING = 0x002F02,
    Item_ELENOR = 0x003002,
    Item_MARK3 = 0x003102,
    Item_MASTER_SYSTEM = 0x003202,
    Item_GENESIS = 0x003302,
    Item_SEGA_SATURN = 0x003402,
    Item_DREAMCAST = 0x003502,
    Item_HAMBURGER = 0x003602,
    Item_PANZERS_TAIL = 0x003702,
    Item_DAVILS_TAIL = 0x003802,
    Item_Monomate = 0x000003,
    Item_Dimate = 0x010003,
    Item_Trimate = 0x020003,
    Item_Monofluid = 0x000103,
    Item_Difluid = 0x010103,
    Item_Trifluid = 0x020103,
    Item_Disk_Lv01 = 0x000203,
    Item_Disk_Lv02 = 0x010203,
    Item_Disk_Lv03 = 0x020203,
    Item_Disk_Lv04 = 0x030203,
    Item_Disk_Lv05 = 0x040203,
    Item_Disk_Lv06 = 0x050203,
    Item_Disk_Lv07 = 0x060203,
    Item_Disk_Lv08 = 0x070203,
    Item_Disk_Lv09 = 0x080203,
    Item_Disk_Lv10 = 0x090203,
    Item_Disk_Lv11 = 0x0A0203,
    Item_Disk_Lv12 = 0x0B0203,
    Item_Disk_Lv13 = 0x0C0203,
    Item_Disk_Lv14 = 0x0D0203,
    Item_Disk_Lv15 = 0x0E0203,
    Item_Disk_Lv16 = 0x0F0203,
    Item_Disk_Lv17 = 0x100203,
    Item_Disk_Lv18 = 0x110203,
    Item_Disk_Lv19 = 0x120203,
    Item_Disk_Lv20 = 0x130203,
    Item_Disk_Lv21 = 0x140203,
    Item_Disk_Lv22 = 0x150203,
    Item_Disk_Lv23 = 0x160203,
    Item_Disk_Lv24 = 0x170203,
    Item_Disk_Lv25 = 0x180203,
    Item_Disk_Lv26 = 0x190203,
    Item_Disk_Lv27 = 0x1A0203,
    Item_Disk_Lv28 = 0x1B0203,
    Item_Disk_Lv29 = 0x1C0203,
    Item_Disk_Lv30 = 0x1D0203,
    Item_Sol_Atomizer = 0x000303,
    Item_Moon_Atomizer = 0x000403,
    Item_Star_Atomizer = 0x000503,
    Item_Antidote = 0x000603,
    Item_Antiparalysis = 0x010603,
    Item_Telepipe = 0x000703,
    Item_Trap_Vision = 0x000803,
    Item_Scape_Doll = 0x000903,
    Item_Monogrinder = 0x000A03,
    Item_Digrinder = 0x010A03,
    Item_Trigrinder = 0x020A03,
    Item_Power_Material = 0x000B03,
    Item_Mind_Material = 0x010B03,
    Item_Evade_Material = 0x020B03,
    Item_HP_Material = 0x030B03,
    Item_TP_Material = 0x040B03,
    Item_Def_Material = 0x050B03,
    Item_Hit_Material = 0x060B03,
    Item_Luck_Material = 0x070B03,
    Item_Cell_of_MAG_502 = 0x000C03,
    Item_Cell_of_MAG_213 = 0x010C03,
    Item_Parts_of_RoboChao = 0x020C03,
    Item_Heart_of_Opa_Opa = 0x030C03,
    Item_Heart_of_Pian = 0x040C03,
    Item_Heart_of_Chao = 0x050C03,
    Item_Sorcerers_Right_Arm = 0x000D03,
    Item_S_beats_Arms = 0x010D03,
    Item_P_arms_Arms = 0x020D03,
    Item_Delsabers_Right_Arm = 0x030D03,
    Item_C_bringers_Right_Arm = 0x040D03,
    Item_Delsabres_Left_Arm = 0x050D03,   /* Spelled as in game */
    Item_Book_of_KATANA1 = 0x060D03,
    Item_Book_of_KATANA2 = 0x070D03,
    Item_Book_of_KATANA3 = 0x080D03,
    Item_S_reds_Arms = 0x000E03,
    Item_Dragons_Claw = 0x010E03,
    Item_Hildebears_Head = 0x020E03,
    Item_Hildeblues_Head = 0x030E03,
    Item_Parts_of_Baranz = 0x040E03,
    Item_Belras_Right_Arm = 0x050E03,
    Item_Joint_Parts = 0x060E03,
    Item_Weapons_Bronze_Badge = 0x070E03,
    Item_Weapons_Silver_Badge = 0x080E03,
    Item_Weapons_Gold_Badge = 0x090E03,
    Item_Weapons_Crystal_Badge = 0x0A0E03,
    Item_Weapons_Steel_Badge = 0x0B0E03,
    Item_Weapons_Aluminum_Badge = 0x0C0E03,
    Item_Weapons_Leather_Badge = 0x0D0E03,
    Item_Weapons_Bone_Badge = 0x0E0E03,
    Item_Letter_of_appreciation = 0x0F0E03,
    Item_Autograph_Album = 0x100E03,
    Item_High_level_Mag_Cell_Eno = 0x110E03,
    Item_High_level_Mag_Armor_Uru = 0x120E03,
    Item_Special_Gene_Flou = 0x130E03,
    Item_Sound_Source_FM = 0x140E03,
    Item_Parts_of_68000 = 0x150E03,
    Item_SH2 = 0x160E03,
    Item_SH4 = 0x170E03,
    Item_Modem = 0x180E03,
    Item_Power_VR = 0x190E03,
    Item_Glory_in_the_past = 0x1A0E03,
    Item_Valentines_Chocolate = 0x1B0E03,
    Item_New_Years_Card = 0x1C0E03,
    Item_Christmas_Card = 0x1D0E03,
    Item_Birthday_Card = 0x1E0E03,
    Item_Proof_of_Sonic_Team = 0x1F0E03,
    Item_Special_Event_Ticket = 0x200E03,
    Item_Flower_Bouquet = 0x210E03,
    Item_Cake = 0x220E03,
    Item_Accessories = 0x230E03,
    Item_Mr_Nakas_Business_Card = 0x240E03,
    Item_AddSlot = 0x000F03,
    Item_Photon_Drop = 0x001003,
    Item_Photon_Sphere = 0x011003,
    Item_Photon_Crystal = 0x021003,
    Item_Meseta = 0x000004,
    Item_NoSuchItem = 0xFFFFFF,
    /* Some odd special cases... */
    Item_Luck_Material_v3 = Item_Hit_Material,
    Item_Invalid_Material_v3 = Item_Luck_Material
} item_code_t;

/* 其他版本物品结构清单 */
typedef struct item_map_s {
    union {
        item_code_t code;
        uint8_t data1b[4];
    };
    const char* name;
} PACKED item_map_t;

#ifndef _WIN32
#else
#pragma pack()
#endif

#undef PACKED

/* 物品名称总清单. 来自 PSOPC. */
static item_map_t item_list[] = {
    { Item_Meseta, "Meseta" },
    { Item_Saber, "Saber" },
    { Item_Brand, "Brand" },
    { Item_Buster, "Buster" },
    { Item_Pallasch, "Pallasch" },
    { Item_Gladius, "Gladius" },
    { Item_DBS_SABER, "DB\'S SABER" },
    { Item_KALADBOLG, "KALADBOLG" },
    { Item_DURANDAL, "DURANDAL" },
    { Item_Sword, "Sword" },
    { Item_Gigush, "Gigush" },
    { Item_Breaker, "Breaker" },
    { Item_Claymore, "Claymore" },
    { Item_Calibur, "Calibur" },
    { Item_FLOWENS_SWORD, "FLOWEN\'S SWORD" },
    { Item_LAST_SURVIVOR, "LAST SURVIVOR" },
    { Item_DRAGON_SLAYER, "DRAGON SLAYER" },
    { Item_Dagger, "Dagger" },
    { Item_Knife, "Knife" },
    { Item_Blade, "Blade" },
    { Item_Edge, "Edge" },
    { Item_Ripper, "Ripper" },
    { Item_BLADE_DANCE, "BLADE DANCE" },
    { Item_BLOODY_ART, "BLOODY ART" },
    { Item_CROSS_SCAR, "CROSS SCAR" },
    { Item_Partisan, "Partisan" },
    { Item_Halbert, "Halbert" },
    { Item_Glaive, "Glaive" },
    { Item_Berdys, "Berdys" },
    { Item_Gungnir, "Gungnir" },
    { Item_BRIONAC, "BRIONAC" },
    { Item_VJAYA, "VJAYA" },
    { Item_GAE_BOLG, "GAE BOLG" },
    { Item_Slicer, "Slicer" },
    { Item_Spinner, "Spinner" },
    { Item_Cutter, "Cutter" },
    { Item_Sawcer, "Sawcer" },
    { Item_Diska, "Diska" },
    { Item_SLICER_OF_ASSASSIN, "SLICER OF ASSASSIN" },
    { Item_DISKA_OF_LIBERATOR, "DISKA OF LIBERATOR" },
    { Item_DISKA_OF_BRAVEMAN, "DISKA OF BRAVEMAN" },
    { Item_Handgun, "Handgun" },
    { Item_Autogun, "Autogun" },
    { Item_Lockgun, "Lockgun" },
    { Item_Railgun, "Railgun" },
    { Item_Raygun, "Raygun" },
    { Item_VARISTA, "VARISTA" },
    { Item_CUSTOM_RAY_ver_OO, "CUSTOM RAY ver.OO" },
    { Item_BRAVACE, "BRAVACE" },
    { Item_Rifle, "Rifle" },
    { Item_Sniper, "Sniper" },
    { Item_Blaster, "Blaster" },
    { Item_Beam, "Beam" },
    { Item_Laser, "Laser" },
    { Item_VISK_235W, "VISK-235W" },
    { Item_WALS_MK2, "WALS-MK2" },
    { Item_JUSTY_23ST, "JUSTY-23ST" },
    { Item_Mechgun, "Mechgun" },
    { Item_Assault, "Assault" },
    { Item_Repeater, "Repeater" },
    { Item_Gatling, "Gatling" },
    { Item_Vulcan, "Vulcan" },
    { Item_M_and_A60_VISE, "M&A60 VISE" },
    { Item_H_and_S25_JUSTICE, "H&S25 JUSTICE" },
    { Item_L_and_K14_COMBAT, "L&K14 COMBAT" },
    { Item_Shot, "Shot" },
    { Item_Spread, "Spread" },
    { Item_Cannon, "Cannon" },
    { Item_Launcher, "Launcher" },
    { Item_Arms, "Arms" },
    { Item_CRUSH_BULLET, "CRUSH BULLET" },
    { Item_METEOR_SMASH, "METEOR SMASH" },
    { Item_FINAL_IMPACT, "FINAL IMPACT" },
    { Item_Cane, "Cane" },
    { Item_Stick, "Stick" },
    { Item_Mace, "Mace" },
    { Item_Club, "Club" },
    { Item_CLUB_OF_LACONIUM, "CLUB OF LACONIUM" },
    { Item_MACE_OF_ADAMAN, "MACE OF ADAMAN" },
    { Item_CLUB_OF_ZUMIURAN, "CLUB OF ZUMIURAN" },
    { Item_Rod, "Rod" },
    { Item_Pole, "Pole" },
    { Item_Pillar, "Pillar" },
    { Item_Striker, "Striker" },
    { Item_BATTLE_VERGE, "BATTLE VERGE" },
    { Item_BRAVE_HAMMER, "BRAVE HAMMER" },
    { Item_ALIVE_AQHU, "ALIVE AQHU" },
    { Item_Wand, "Wand" },
    { Item_Staff, "Staff" },
    { Item_Baton, "Baton" },
    { Item_Scepter, "Scepter" },
    { Item_FIRE_SCEPTER_AGNI, "FIRE SCEPTER:AGNI" },
    { Item_ICE_STAFF_DAGON, "ICE STAFF:DAGON" },
    { Item_STORM_WAND_INDRA, "STORM WAND:INDRA" },
    { Item_PHOTON_CLAW, "PHOTON CLAW" },
    { Item_SILENCE_CLAW, "SILENCE CLAW" },
    { Item_NEIS_CLAW, "NEI\'S CLAW" },
    { Item_DOUBLE_SABER, "DOUBLE SABER" },
    { Item_STAG_CUTLERY, "STAG CUTLERY" },
    { Item_TWIN_BRAND, "TWIN BRAND" },
    { Item_BRAVE_KNUCKLE, "BRAVE KNUCKLE" },
    { Item_ANGRY_FIST, "ANGRY FIST" },
    { Item_GOD_HAND, "GOD HAND" },
    { Item_SONIC_KNUCKLE, "SONIC KNUCKLE" },
    { Item_OROTIAGITO_alt, "OROTIAGITO (alt)" },
    { Item_OROTIAGITO, "OROTIAGITO" },
    { Item_AGITO_1975, "AGITO (AUW 1975)" },
    { Item_AGITO_1983, "AGITO (AUW 1983)" },
    { Item_AGITO_2001, "AGITO (AUW 2001)" },
    { Item_AGITO_1991, "AGITO (AUW 1991)" },
    { Item_AGITO_1977, "AGITO (AUW 1977)" },
    { Item_AGITO_1980, "AGITO (AUW 1980)" },
    { Item_SOUL_EATER, "SOUL EATER" },
    { Item_SOUL_BANISH, "SOUL BANISH" },
    { Item_SPREAD_NEEDLE, "SPREAD NEEDLE" },
    { Item_HOLY_RAY, "HOLY RAY" },
    { Item_INFERNO_BAZOOKA, "INFERNO BAZOOKA" },
    { Item_FLAME_VISIT, "FLAME VISIT" },
    { Item_AKIKOS_FRYING_PAN, "AKIKO\'S FRYING PAN" },
    { Item_C_SORCERERS_CANE, "C-SORCERER\'S CANE" },
    { Item_S_BEATS_BLADE, "S-BEAT\'S BLADE" },
    { Item_P_ARMSS_BLADE, "P-ARMS\'S BLADE" },
    { Item_DELSABERS_BUSTER, "DELSABER\'S BUSTER" },
    { Item_C_BRINGERS_RIFLE, "C-BRINGER\'S RIFLE" },
    { Item_EGG_BLASTER, "EGG BLASTER" },
    { Item_PSYCHO_WAND, "PSYCHO WAND" },
    { Item_HEAVEN_PUNISHER, "HEAVEN PUNISHER" },
    { Item_LAVIS_CANNON, "LAVIS CANNON" },
    { Item_VICTOR_AXE, "VICTOR AXE" },
    { Item_CHAIN_SAWD, "CHAIN SAWD" },
    { Item_CADUCEUS, "CADUCEUS" },
    { Item_STING_TIP, "STING TIP" },
    { Item_MAGICAL_PIECE, "MAGICAL PIECE" },
    { Item_TECHNICAL_CROZIER, "TECHNICAL CROZIER" },
    { Item_SUPPRESSED_GUN, "SUPPRESSED GUN" },
    { Item_ANCIENT_SABER, "ANCIENT SABER" },
    { Item_HARISEN_BATTLE_FAN, "HARISEN BATTLE FAN" },
    { Item_YAMIGARASU, "YAMIGARASU" },
    { Item_AKIKOS_WOK, "AKIKO\'S WOK" },
    { Item_TOY_HAMMER, "TOY HAMMER" },
    { Item_ELYSION, "ELYSION" },
    { Item_RED_SABER, "RED SABER" },
    { Item_METEOR_CUDGEL, "METEOR CUDGEL" },
    { Item_MONKEY_KING_BAR, "MONKEY KING BAR" },
    { Item_DOUBLE_CANNON, "DOUBLE CANNON" },
    { Item_HUGE_BATTLE_FAN, "HUGE BATTLE FAN" },
    { Item_TSUMIKIRI_J_SWORD, "TSUMIKIRI J-SWORD" },
    { Item_SEALED_J_SWORD, "SEALED J-SWORD" },
    { Item_RED_SWORD, "RED SWORD" },
    { Item_CRAZY_TUNE, "CRAZY TUNE" },
    { Item_TWIN_CHAKRAM, "TWIN CHAKRAM" },
    { Item_WOK_OF_AKIKOS_SHOP, "WOK OF AKIKO\'S SHOP" },
    { Item_LAVIS_BLADE, "LAVIS BLADE" },
    { Item_RED_DAGGER, "RED DAGGER" },
    { Item_MADAMS_PARASOL, "MADAM\'S PARASOL" },
    { Item_MADAMS_UMBRELLA, "MADAM\'S UMBRELLA" },
    { Item_IMPERIAL_PICK, "IMPERIAL PICK" },
    { Item_BERDYSH, "BERDYSH" },
    { Item_RED_PARTISAN, "RED PARTISAN" },
    { Item_FLIGHT_CUTTER, "FLIGHT CUTTER" },
    { Item_FLIGHT_FAN, "FLIGHT FAN" },
    { Item_RED_SLICER, "RED SLICER" },
    { Item_HANDGUN_GULD, "HANDGUN:GULD" },
    { Item_HANDGUN_MILLA, "HANDGUN:MILLA" },
    { Item_RED_HANDGUN, "RED HANDGUN" },
    { Item_FROZEN_SHOOTER, "FROZEN SHOOTER" },
    { Item_ANTI_ANDROID_RIFLE, "ANTI ANDROID RIFLE" },
    { Item_ROCKET_PUNCH, "ROCKET PUNCH" },
    { Item_SAMBA_MARACAS, "SAMBA MARACAS" },
    { Item_TWIN_PSYCHOGUN, "TWIN PSYCHOGUN" },
    { Item_DRILL_LAUNCHER, "DRILL LAUNCHER" },
    { Item_GULD_MILLA, "GULD MILLA" },
    { Item_RED_MECHGUN, "RED MECHGUN" },
    { Item_BERLA_CANNON, "BERLA CANNON" },
    { Item_PANZER_FAUST, "PANZER FAUST" },
    { Item_SUMMIT_MOON, "SUMMIT MOON" },
    { Item_WINDMILL, "WINDMILL" },
    { Item_EVIL_CURST, "EVIL CURST" },
    { Item_FLOWER_CANE, "FLOWER CANE" },
    { Item_HILDEBEARS_CANE, "HILDEBEAR\'S CANE" },
    { Item_HILDEBLUES_CANE, "HILDEBLUE\'S CANE" },
    { Item_RABBIT_WAND, "RABBIT WAND" },
    { Item_PLANTAIN_LEAF, "PLANTAIN LEAF" },
    { Item_DEMONIC_FORK, "DEMONIC FORK" },
    { Item_STRIKER_OF_CHAO, "STIRKER OF CHAO" },
    { Item_BROOM, "BROOM" },
    { Item_PROPHETS_OF_MOTAV, "PROPHETS OF MOTAV" },
    { Item_THE_SIGH_OF_A_GOD, "THE SIGH OF A GOD" },
    { Item_TWINKLE_STAR, "TWINKLE STAR" },
    { Item_PLANTAIN_FAN, "PLANTAIN FAN" },
    { Item_TWIN_BLAZE, "TWIN BLAZE" },
    { Item_MARINAS_BAG, "MARINA\'S BAG" },
    { Item_DRAGONS_CLAW, "DRAGON\'S CLAW" },
    { Item_PANTHERS_CLAW, "PANTHER\'S CLAW" },
    { Item_S_REDS_BLADE, "S-RED\'S BLADE" },
    { Item_PLANTAIN_HUGE_FAN, "PLANTAIN HUGE FAN" },
    { Item_CHAMELEON_SCYTHE, "CHAMELEON SCYTHE" },
    { Item_YASMINKOV_3000R, "YASMINKOV 3000R" },
    { Item_ANO_RIFLE, "ANO RIFLE" },
    { Item_BARANZ_LAUNCHER, "BARANZ LAUNCHER" },
    { Item_BRANCH_OF_PAKUPAKU, "BRANCH OF PAKUPAKU" },
    { Item_HEART_OF_POUMN, "HEART OF POUMN" },
    { Item_YASMINKOV_2000H, "YASMINKOV 2000H" },
    { Item_YASMINKOV_7000V, "YASMINKOV 7000V" },
    { Item_YASMINKOV_9200M, "YASMINKOV 9200M" },
    { Item_MASER_BEAM, "MASER BEAM" },
    { Item_GAME_MAGAZNE, "GAME MAGAZNE" },
    { Item_FLOWER_BOUQUET, "FLOWER BOUQUET" },
    { Item_SRANK_SABER, "SABER" },
    { Item_SRANK_SWORD, "SWORD" },
    { Item_SRANK_BLADE, "BLADE" },
    { Item_SRANK_PARTISAN, "PARTISAN" },
    { Item_SRANK_SLICER, "SLICER" },
    { Item_SRANK_GUN, "GUN" },
    { Item_SRANK_RIFLE, "RIFLE" },
    { Item_SRANK_MECHGUN, "MECHGUN" },
    { Item_SRANK_SHOT, "SHOT" },
    { Item_SRANK_CANE, "CANE" },
    { Item_SRANK_ROD, "ROD" },
    { Item_SRANK_WAND, "WAND" },
    { Item_SRANK_TWIN, "TWIN" },
    { Item_SRANK_CLAW, "CLAW" },
    { Item_SRANK_BAZOOKA, "BAZOOKA" },
    { Item_SRANK_NEEDLE, "NEEDLE" },
    { Item_SRANK_SCYTHE, "SCYTHE" },
    { Item_SRANK_HAMMER, "HAMMER" },
    { Item_SRANK_MOON, "MOON" },
    { Item_SRANK_PSYCHOGUN, "PSYCHOGUN" },
    { Item_SRANK_PUNCH, "PUNCH" },
    { Item_SRANK_WINDMILL, "WINDMILL" },
    { Item_SRANK_HARISEN, "HARISEN" },
    { Item_SRANK_J_BLADE, "J-BLADE" },
    { Item_SRANK_J_CUTTER, "J-CUTTER" },
    { Item_Frame, "Frame" },
    { Item_Armor, "Armor" },
    { Item_Psy_Armor, "Psy Armor" },
    { Item_Giga_Frame, "Giga Frame" },
    { Item_Soul_Frame, "Soul Frame" },
    { Item_Cross_Armor, "Cross Armor" },
    { Item_Solid_Frame, "Solid Frame" },
    { Item_Brave_Armor, "Brace Armor" },
    { Item_Hyper_Frame, "Hyper Frame" },
    { Item_Grand_Armor, "Grand Armor" },
    { Item_Shock_Frame, "Shock Frame" },
    { Item_Kings_Frame, "King\'s Frame" },
    { Item_Dragon_Frame, "Dragon Frame" },
    { Item_Absorb_Armor, "Absorb Armor" },
    { Item_Protect_Frame, "Protect Frame" },
    { Item_General_Armor, "General Armor" },
    { Item_Perfect_Frame, "Perfect Frame" },
    { Item_Valiant_Frame, "Valiant Frame" },
    { Item_Imperial_Armor, "Imperial Armor" },
    { Item_Holiness_Armor, "Holiness Armor" },
    { Item_Guardian_Armor, "Guardian Armor" },
    { Item_Divinity_Armor, "Divinity Armor" },
    { Item_Ultimate_Frame, "Ultimate Frame" },
    { Item_Celestial_Armor, "Celestial Armor" },
    { Item_HUNTER_FIELD, "HUNTER FIELD" },
    { Item_RANGER_FIELD, "RANGER FIELD" },
    { Item_FORCE_FIELD, "FORCE FIELD" },
    { Item_REVIVAL_GARMENT, "REVIVAL GARMENT" },
    { Item_SPIRIT_GARMENT, "SPIRIT GARMENT" },
    { Item_STINK_FRAME, "STINK FRAME" },
    { Item_D_PARTS_ver1_01, "D-PARTS ver1.01" },
    { Item_D_PARTS_ver2_10, "D-PARTS ver2.10" },
    { Item_PARASITE_WEAR_De_Rol, "PARASITE WEAR:De Rol" },
    { Item_PARASITE_WEAR_Nelgal, "PARASITE WEAR:Nelgal" },
    { Item_PARASITE_WEAR_Vajulla, "PARASITE WEAR:Vajulla" },
    { Item_SENSE_PLATE, "SENSE PLATE" },
    { Item_GRAVITON_PLATE, "GRAVITON PLATE" },
    { Item_ATTRIBUTE_PLATE, "ATTRIBUTE PLATE" },
    { Item_FLOWENS_FRAME, "FLOWEN\'S FRAME" },
    { Item_CUSTOM_FRAME_ver_OO, "CUSTOM FRAME ver.OO" },
    { Item_DBS_ARMOR, "DB\'S ARMOR" },
    { Item_GUARD_WAVE, "GUARD WAVE" },
    { Item_DF_FIELD, "DF FIELD" },
    { Item_LUMINOUS_FIELD, "LUMINOUS FIELD" },
    { Item_CHU_CHU_FEVER, "CHU CHU FEVER" },
    { Item_LOVE_HEART, "LOVE HEART" },
    { Item_FLAME_GARMENT, "FLAME GARMENT" },
    { Item_VIRUS_ARMOR_Lafuteria, "VIRUS ARMOR:Lafuteria" },
    { Item_BRIGHTNESS_CIRCLE, "BRIGHTNESS CIRCLE" },
    { Item_AURA_FIELD, "AURA FIELD" },
    { Item_ELECTRO_FRAME, "ELECTRO FRAME" },
    { Item_SACRED_CLOTH, "SACRED CLOTH" },
    { Item_SMOKING_PLATE, "SMOKING PLATE" },
    { Item_Barrier, "Barrier" },
    { Item_Shield, "Shield" },
    { Item_Core_Shield, "Core Shield" },
    { Item_Giga_Shield, "Giga Shield" },
    { Item_Soul_Barrier, "Soul Barrier" },
    { Item_Hard_Shield, "Hard Shield" },
    { Item_Brave_Barrier, "Brave Barrier" },
    { Item_Solid_Shield, "Solid Shield" },
    { Item_Flame_Barrier, "Flame Barrier" },
    { Item_Plasma_Barrier, "Plasma Barrier" },
    { Item_Freeze_Barrier, "Freeze Barrier" },
    { Item_Psychic_Barrier, "Psychic Barrier" },
    { Item_General_Shield, "General Shield" },
    { Item_Protect_Barrier, "Protect Barrier" },
    { Item_Glorious_Shield, "Glorious Shield" },
    { Item_Imperial_Barrier, "Imperial Barrier" },
    { Item_Guardian_Shield, "Guardian Shield" },
    { Item_Divinity_Barrier, "Divinity Barrier" },
    { Item_Ultimate_Shield, "Ultimate Shield" },
    { Item_Spiritual_Shield, "Spiritual Shield" },
    { Item_Celestial_Shield, "Celestial Shield" },
    { Item_INVISIBLE_GUARD, "INVISIBLE GUARD" },
    { Item_SACRED_GUARD, "SACRED GUARD" },
    { Item_S_PARTS_ver1_16, "S-PARTS ver1.16" },
    { Item_S_PARTS_ver2_01, "S-PARTS ver2.01" },
    { Item_LIGHT_RELIEF, "LIGHT RELIEF" },
    { Item_SHIELD_OF_DELSABER, "SHIELD OF DELSABER" },
    { Item_FORCE_WALL, "FORCE WALL" },
    { Item_RANGER_WALL, "RANGER WALL" },
    { Item_HUNTER_WALL, "HUNTER WALL" },
    { Item_ATTRIBUTE_WALL, "ATTRIBUTE WALL" },
    { Item_SECRET_GEAR, "SECRET GEAR" },
    { Item_COMBAT_GEAR, "COMBAT GEAR" },
    { Item_PROTO_REGENE_GEAR, "PROTO REGENE GEAR" },
    { Item_REGENERATE_GEAR, "REGENERATE GEAR" },
    { Item_REGENE_GEAR_ADV, "REGENE GEAR ADV" },
    { Item_FLOWENS_SHIELD, "FLOWEN\'S SHIELD" },
    { Item_CUSTOM_BARRIER_ver_OO, "CUSTOM BARRIER ver.OO" },
    { Item_DBS_SHIELD, "DB\'S SHIELD" },
    { Item_RED_RING, "RED RING" },
    { Item_TRIPOLIC_SHIELD, "TRIPOLIC SHIELD" },
    { Item_STANDSTILL_SHIELD, "STANDSTILL SHIELD" },
    { Item_SAFETY_HEART, "SAFETY HEART" },
    { Item_KASAMI_BRACER, "KASAMI BRACER" },
    { Item_GODS_SHIELD_SUZAKU, "GODS SHIELD SUZAKU" },
    { Item_GODS_SHIELD_GENBU, "GODS SHIELD GENBU" },
    { Item_GODS_SHIELD_BYAKKO, "GODS SHIELD BYAKKO" },
    { Item_GODS_SHIELD_SEIRYU, "GODS SHIELD SEIRYU" },
    { Item_HANTERS_SHELL, "HANTER\'S SHELL" },
    { Item_RIKOS_GLASSES, "RIKO\'S GLASSES" },
    { Item_RIKOS_EARRING, "RIKO\'S EARRING" },
    { Item_BLUE_RING, "BLUE RING" },
    { Item_YELLOW_RING, "YELLOW RING" },
    { Item_SECURE_FEET, "SECURE FEET" },
    { Item_PURPLE_RING, "PURPLE RING" },
    { Item_GREEN_RING, "GREEN RING" },
    { Item_BLACK_RING, "BLACK RING" },
    { Item_WHITE_RING, "WHITE RING" },
    { Item_Knight_Power, "Knight/Power" },
    { Item_General_Power, "General/Power" },
    { Item_Ogre_Power, "Ogre/Power" },
    { Item_God_Power, "God/Power" },
    { Item_Priest_Mind, "Priest/Mind" },
    { Item_General_Mind, "General/Mind" },
    { Item_Angel_Mind, "Angel/Mind" },
    { Item_God_Mind, "God/Mind" },
    { Item_Marksman_Arm, "Marksman/Arm" },
    { Item_General_Arm, "General/Arm" },
    { Item_Elf_Arm, "Elf/Arm" },
    { Item_God_Arm, "God/Arm" },
    { Item_Thief_Legs, "Thief/Legs" },
    { Item_General_Legs, "General/Legs" },
    { Item_Elf_Legs, "Elf/Legs" },
    { Item_God_Legs, "God/Legs" },
    { Item_Digger_HP, "Digger/HP" },
    { Item_General_HP, "General/HP" },
    { Item_Dragon_HP, "Dragon/HP" },
    { Item_God_HP, "God/HP" },
    { Item_Magician_TP, "Magician/TP" },
    { Item_General_TP, "General/TP" },
    { Item_Angel_TP, "Angel/TP" },
    { Item_God_TP, "God/TP" },
    { Item_Warrior_Body, "Warrior/Body" },
    { Item_General_Body, "General/Body" },
    { Item_Metal_Body, "Metal/Body" },
    { Item_God_Body, "God/Body", },
    { Item_Angel_Luck, "Angel/Luck" },
    { Item_God_Luck, "God/Luck" },
    { Item_Master_Ability, "Master/Ability" },
    { Item_Hero_Ability, "Hero/Ability" },
    { Item_God_Ability, "God/Ability" },
    { Item_Resist_Fire, "Resist/Fire" },
    { Item_Resist_Flame, "Resist/Flame" },
    { Item_Resist_Burning, "Resist/Burning" },
    { Item_Resist_Cold, "Resist/Cold" },
    { Item_Resist_Freeze, "Resist/Freeze" },
    { Item_Resist_Blizzard, "Resist/Blizzard" },
    { Item_Resist_Shock, "Resist/Shock" },
    { Item_Resist_Thunder, "Resist/Thunder" },
    { Item_Resist_Storm, "Resist/Storm" },
    { Item_Resist_Light, "Resist/Light" },
    { Item_Resist_Saint, "Resist/Saint" },
    { Item_Resist_Holy, "Resist/Holy" },
    { Item_Resist_Dark, "Resist/Dark" },
    { Item_Resist_Evil, "Resist/Evil" },
    { Item_Resist_Devil, "Resist/Devil" },
    { Item_All_Resist, "All/Resist" },
    { Item_Super_Resist, "Super/Resist" },
    { Item_Perfect_Resist, "Perfect/Resist" },
    { Item_HP_Restorate, "HP/Restorate" },
    { Item_HP_Generate, "HP/Generate" },
    { Item_HP_Revival, "HP/Revival" },
    { Item_TP_Restorate, "TP/Restorate" },
    { Item_TP_Generate, "TP/Generate" },
    { Item_TP_Revival, "TP/Revival" },
    { Item_PB_Amplifier, "PB/Amplifier" },
    { Item_PB_Generate, "PB/Generate" },
    { Item_PB_Create, "PB/Create" },
    { Item_Wizard_Technique, "Wizard/Technique" },
    { Item_Devil_Technique, "Devil/Technique" },
    { Item_God_Technique, "God/Technique" },
    { Item_General_Battle, "General/Battle" },
    { Item_Devil_Battle, "Devil/Battle" },
    { Item_God_Battle, "God/Battle" },
    { Item_State_Maintenance, "State/Maintenance" },
    { Item_Trap_Search, "Trap/Search" },
    { Item_Mag, "Mag" },
    { Item_Varuna, "Varuna" },
    { Item_Mitra, "Mitra" },
    { Item_Surya, "Surya" },
    { Item_Vayu, "Vayu" },
    { Item_Varaha, "Varaha" },
    { Item_Kama, "Kama" },
    { Item_Ushasu, "Ushasu" },
    { Item_Apsaras, "Apsaras" },
    { Item_Kumara, "Kumara" },
    { Item_Kaitabha, "Kaitabha" },
    { Item_Tapas, "Tapas" },
    { Item_Bhirava, "Bhirava" },
    { Item_Kalki, "Kalki" },
    { Item_Rudra, "Rudra" },
    { Item_Marutah, "Marutah" },
    { Item_Yaksa, "Yaksa" },
    { Item_Sita, "Sita" },
    { Item_Garuda, "Garuda" },
    { Item_Nandin, "Nandin" },
    { Item_Ashvinau, "Ashvinau" },
    { Item_Ribhava, "Ribhava" },
    { Item_Soma, "Soma" },
    { Item_Ila, "Ila" },
    { Item_Durga, "Durga" },
    { Item_Vritra, "Vritra" },
    { Item_Namuci, "Namuci" },
    { Item_Sumba, "Sumba" },
    { Item_Naga, "Naga" },
    { Item_Pitri, "Pitri" },
    { Item_Kabanda, "Kabanda" },
    { Item_Ravana, "Ravana" },
    { Item_Marica, "Marica" },
    { Item_Soniti, "Soniti" },
    { Item_Preta, "Preta" },
    { Item_Andhaka, "Andhaka" },
    { Item_Bana, "Bana" },
    { Item_Naraka, "Naraka" },
    { Item_Madhu, "Madhu" },
    { Item_Churel, "Churel" },
    { Item_ROBOCHAO, "ROBOCHAO" },
    { Item_OPA_OPA, "OPA-OPA" },
    { Item_PIAN, "PIAN" },
    { Item_CHAO, "CHAO" },
    { Item_CHU_CHU, "CHU CHU" },
    { Item_KAPU_KAPU, "KAPU KAPU" },
    { Item_ANGELS_WING, "ANGEL\'S WING" },
    { Item_DEVILS_WING, "DEVIL\'S WING" },
    { Item_ELENOR, "ELENOR" },
    { Item_MARK3, "MARK3" },
    { Item_MASTER_SYSTEM, "MASTER SYSTEM" },
    { Item_GENESIS, "GENESIS" },
    { Item_SEGA_SATURN, "SEGA SATURN" },
    { Item_DREAMCAST, "DREAMCAST" },
    { Item_HAMBURGER, "HAMBURGER" },
    { Item_PANZERS_TAIL, "PANZER\'S TAIL" },
    { Item_DAVILS_TAIL, "DAVIL\'S TAIL" },
    { Item_Monomate, "Monomate" },
    { Item_Dimate, "Dimate" },
    { Item_Trimate, "Trimate" },
    { Item_Monofluid, "Monofluid" },
    { Item_Difluid, "Difluid" },
    { Item_Trifluid, "Trifluid" },
    { Item_Disk_Lv01, "Disk:Lv.1" },
    { Item_Disk_Lv02, "Disk:Lv.2" },
    { Item_Disk_Lv03, "Disk:Lv.3" },
    { Item_Disk_Lv04, "Disk:Lv.4" },
    { Item_Disk_Lv05, "Disk:Lv.5" },
    { Item_Disk_Lv06, "Disk:Lv.6" },
    { Item_Disk_Lv07, "Disk:Lv.7" },
    { Item_Disk_Lv08, "Disk:Lv.8" },
    { Item_Disk_Lv09, "Disk:Lv.9" },
    { Item_Disk_Lv10, "Disk:Lv.10" },
    { Item_Disk_Lv11, "Disk:Lv.11" },
    { Item_Disk_Lv12, "Disk:Lv.12" },
    { Item_Disk_Lv13, "Disk:Lv.13" },
    { Item_Disk_Lv14, "Disk:Lv.14" },
    { Item_Disk_Lv15, "Disk:Lv.15" },
    { Item_Disk_Lv16, "Disk:Lv.16" },
    { Item_Disk_Lv17, "Disk:Lv.17" },
    { Item_Disk_Lv18, "Disk:Lv.18" },
    { Item_Disk_Lv19, "Disk:Lv.19" },
    { Item_Disk_Lv20, "Disk:Lv.20" },
    { Item_Disk_Lv21, "Disk:Lv.21" },
    { Item_Disk_Lv22, "Disk:Lv.22" },
    { Item_Disk_Lv23, "Disk:Lv.23" },
    { Item_Disk_Lv24, "Disk:Lv.24" },
    { Item_Disk_Lv25, "Disk:Lv.25" },
    { Item_Disk_Lv26, "Disk:Lv.26" },
    { Item_Disk_Lv27, "Disk:Lv.27" },
    { Item_Disk_Lv28, "Disk:Lv.28" },
    { Item_Disk_Lv29, "Disk:Lv.29" },
    { Item_Disk_Lv30, "Disk:Lv.30" },
    { Item_Sol_Atomizer, "Sol Atomizer" },
    { Item_Moon_Atomizer, "Moon Atomizer" },
    { Item_Star_Atomizer, "Star Atomizer" },
    { Item_Antidote, "Antidote" },
    { Item_Antiparalysis, "Antiparalysis" },
    { Item_Telepipe, "Telepipe" },
    { Item_Trap_Vision, "Trap Vision" },
    { Item_Scape_Doll, "Scape Doll" },
    { Item_Monogrinder, "Monogrinder" },
    { Item_Digrinder, "Digrinder" },
    { Item_Trigrinder, "Trigrinder" },
    { Item_Power_Material, "Power Material" },
    { Item_Mind_Material, "Mind Material" },
    { Item_Evade_Material, "Evade Material" },
    { Item_HP_Material, "HP Material" },
    { Item_TP_Material, "TP Material" },
    { Item_Def_Material, "Def Material" },
    { Item_Hit_Material, "Hit Material" },
    { Item_Luck_Material, "Luck Material" },
    { Item_Cell_of_MAG_502, "Cell of MAG 502" },
    { Item_Cell_of_MAG_213, "Cell of MAG 213" },
    { Item_Parts_of_RoboChao, "Parts of RoboChao" },
    { Item_Heart_of_Opa_Opa, "Heart of Opa Opa" },
    { Item_Heart_of_Pian, "Heart of Pian" },
    { Item_Heart_of_Chao, "Heart of Chao" },
    { Item_Sorcerers_Right_Arm, "Sorcerer\'s Right Arm" },
    { Item_S_beats_Arms, "S-beat\'s Arms" },
    { Item_P_arms_Arms, "P-arm\'s Arms" },
    { Item_Delsabers_Right_Arm, "Delsaber\'s Right Arm" },
    { Item_C_bringers_Right_Arm, "C-bringer\'s Right Arm" },
    { Item_Delsabres_Left_Arm, "Delsabre\'s Left Arm" },
    { Item_Book_of_KATANA1, "Book of KATANA1" },
    { Item_Book_of_KATANA2, "Book of KATANA2" },
    { Item_Book_of_KATANA3, "Book of KATANA3" },
    { Item_S_reds_Arms, "S-red\'s Arms" },
    { Item_Dragons_Claw, "Dragon\'s Claw" },
    { Item_Hildebears_Head, "Hildebear\'s Head" },
    { Item_Hildeblues_Head, "Hildeblue\'s Head" },
    { Item_Parts_of_Baranz, "Parts of Baranz" },
    { Item_Belras_Right_Arm, "Belra\'s Right Arm" },
    { Item_Joint_Parts, "Joint Parts" },
    { Item_Weapons_Bronze_Badge, "Weapons Bronze Badge" },
    { Item_Weapons_Silver_Badge, "Weapons Silver Badge" },
    { Item_Weapons_Gold_Badge, "Weapons Gold Badge" },
    { Item_Weapons_Crystal_Badge, "Weapons Crystal Badge" },
    { Item_Weapons_Steel_Badge, "Weapons Steel Badge" },
    { Item_Weapons_Aluminum_Badge, "Weapons Aluminum Badge" },
    { Item_Weapons_Leather_Badge, "Weapons Leather Badge" },
    { Item_Weapons_Bone_Badge, "Weapons Bone Badge" },
    { Item_Letter_of_appreciation, "Letter of appreciation" },
    { Item_Autograph_Album, "Autograph Album" },
    { Item_High_level_Mag_Cell_Eno, "High-level Mag Cell, Eno" },
    { Item_High_level_Mag_Armor_Uru, "High-level Mag Armor, Uru" },
    { Item_Special_Gene_Flou, "Special Gene Flou" },
    { Item_Sound_Source_FM, "Sound Source FM" },
    { Item_Parts_of_68000, "Parts of 68000" },
    { Item_SH2, "SH2" },
    { Item_SH4, "SH4" },
    { Item_Modem, "Modem" },
    { Item_Power_VR, "Power VR" },
    { Item_Glory_in_the_past, "Glory in the past" },
    { Item_Valentines_Chocolate, "Valentine\'s Chocolate" },
    { Item_New_Years_Card, "New Year\'s Card" },
    { Item_Christmas_Card, "Christmas Card" },
    { Item_Birthday_Card, "Birthday Card" },
    { Item_Proof_of_Sonic_Team, "Proof of Sonic Team" },
    { Item_Special_Event_Ticket, "Special Event Ticket" },
    { Item_Flower_Bouquet, "Flower Bouquet" },
    { Item_Cake, "Cake" },
    { Item_Accessories, "Accessories" },
    { Item_Mr_Nakas_Business_Card, "Mr.Naka\'s Business Card" },
    { Item_NoSuchItem, "" }
};

#endif // !PSOCN_ITEM_LIST_H